#!/usr/bin/bash

# Define default user id
source $(dirname "$0")/om_config.sh

# Check if user id is provided
if [ $# -eq 2 ]; then
    user_id=$1
    job_id=$2
elif [ $# -eq 1 ]; then
    job_id=$1
else
    echo "Usage: om_cancel [user_id] job_id"
    exit 1
fi

if [ "$job_id" = "all" ]; then
    job_id=""
fi

ssh $user_id@openmind.mit.edu "scancel -u $user_id $job_id"

if [ -z "$job_id" ]; then
    echo "All jobs cancelled"
else
    echo "Job $job_id cancelled"
fi