#!/usr/bin/bash

# Define default user id
user_id="valmiki"

# Check if user id is provided
if [ $# -eq 2 ]; then
    user_id=$1
    job_id=$2
elif [ $# -eq 1 ]; then
    job_id=$1
else
    echo "Usage: om_cancel [user_id] job_id"
    exit 1
fi

ssh $user_id@openmind.mit.edu "scancel $jobid"
echo "Job $jobid cancelled"