#!/usr/bin/env bash

set -e

script_dir=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
source $script_dir/om_config.sh

if [ $# -eq 1 ]; then
    job_id=$1
else
    echo "Error: $0 takes exactly one argument"
    echo "Usage: om_cancel job_id"
    exit 1
fi

if [ "$job_id" = "--all" ]; then
    job_id=""
fi

ssh $remote_user@$remote_login_server "scancel -u $remote_user $job_id"

if [ -z "$job_id" ]; then
    echo "All jobs cancelled"
else
    echo "Job $job_id cancelled"
fi