#!/usr/bin/env bash

set -e

# Source the configuration variables
script_dir=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
source $script_dir/om_config.sh

# Initialize function return variables
job_id=""
node_id=""
node_status=""

# Function definitions
SCPSCRIPT() {
    ssh -q $remote_user@$remote_login_server "mkdir -p $remote_script_dir"
    scp -q $script_dir/$jupyter_script $remote_user@$remote_login_server:$remote_script_dir
    ssh -q $remote_user@$remote_login_server "cd $remote_script_dir && sed -i 's/\r//g' $jupyter_script"
}

SUBMITJOB() {
    echo "Starting VSCode Server"
    local ret=$(ssh $remote_user@$remote_login_server "cd $remote_script_dir && sbatch $@ --output=$jupyter_out $jupyter_script --port=$remote_port")
    job_id=$(echo "$ret" | grep -oE '[0-9]+')
    echo "Job $job_id submitted"
}

WAITFORNODE() {
    for ((i = 0 ; i < timeout_limit ; i += 5 )); do
        node_status=$(ssh $remote_user@$remote_login_server "squeue -u $remote_user -j $job_id --format=%T --sort=-V --noheader")
        if [ "$node_status" == "RUNNING" ]; then
            return
        fi
        echo "Node not running, status: $node_status"
        echo "Waiting 5s for node to run"
        sleep 5
    done
}

GETNODEID() {
    node_id=$(ssh $remote_user@$remote_login_server "squeue -u $remote_user -j $job_id --format=%N --sort=-V --noheader")
}

PRINTSERVER() {
    echo "Printing server address"
    server_address=$(ssh $remote_user@$remote_login_server "grep -o \"http://127.0.0.1:$remote_port/lab?token=\S.*\" $remote_script_dir/$jupyter_out | head -n 1")
    echo ${server_address/$remote_port/$local_port}
}

TUNNEL() {
    echo "Starting SSH tunnel to $node_id from local port $local_port to remote port $remote_port"
    echo "Do not close this terminal window until you are done with the server"
    ssh -L $local_port:$node_id:$remote_port $remote_user@$remote_login_server
}

# Call functions
SCPSCRIPT
SUBMITJOB "$@" # returns job_id
WAITFORNODE # returns node_status
if [ "$node_status" == "RUNNING" ]; then
    GETNODEID # returns node_id
    echo "Node $node_id is $node_status"
    echo "Just give the server a few seconds to be ready"
    sleep 30
    PRINTSERVER
    TUNNEL
else
    echo "Job $job_id request has timed out after 2 minutes"
    om_cancel $remote_user $job_id
fi