#!/usr/bin/bash

# Source the configuration variables
root=$(dirname $(readlink -f $0))
source $root/om_config.sh

# Initialize function return variables
job_id=""
node_id=""
node_status=""


SCPSCRIPT() {
    ssh -q $user_id@openmind.mit.edu "mkdir -p $remote_script_dir"
    scp -q $local_script_dir/$jupyter_script $user_id@openmind.mit.edu:$remote_script_dir
    ssh -q $user_id@openmind.mit.edu "cd $remote_script_dir && sed -i 's/\r//g' $jupyter_script"
}

# Function definitions
SUBMITJOB() {
    echo "Starting VSCode Server"
    local ret=$(ssh $user_id@openmind.mit.edu "cd $remote_script_dir && sbatch $@ --output=$jupyter_out $jupyter_script --port=$remote_port")
    job_id=$(echo "$ret" | grep -oE '[0-9]+')
    echo "Job $job_id submitted"
}

WAITFORNODE() {
    for ((i = 0 ; i < timeout_limit ; i += 5 )); do
        node_status=$(ssh $user_id@openmind.mit.edu "squeue -u $user_id -j $job_id --format=%T --sort=-V --noheader")
        if [ "$node_status" == "RUNNING" ]; then
            return
        fi
        echo "Node not running, status: $node_status"
        echo "Waiting 5s for node to run"
        sleep 5
    done
}

GETNODEID() {
    node_id=$(ssh $user_id@openmind.mit.edu "squeue -u $user_id -j $job_id --format=%N --sort=-V --noheader")
}

PRINTSERVER() {
    echo "Printing server address"
    server_address=$(ssh $user_id@openmind.mit.edu "grep -o \"http://127.0.0.1:$remote_port/lab?token=\S.*\" $remote_script_dir/$jupyter_out | head -n 1")
    echo ${server_address/$remote_port/$local_port}
}

TUNNEL() {
    echo "Starting SSH tunnel to $node_id from local port $local_port to remote port $remote_port"
    ssh -L $local_port:$node_id:$remote_port $user_id@openmind.mit.edu
}

# Call functions
SCPSCRIPT
SUBMITJOB "$@" # returns job_id
WAITFORNODE # returns node_status
if [ "$node_status" == "RUNNING" ]; then
    GETNODEID # returns node_id
    echo "Node $node_id is $node_status"
    echo "Just give the server a few seconds to be ready"
    sleep 30
    PRINTSERVER
    TUNNEL
else
    echo "Job $job_id request has timed out after 2 minutes"
    om_cancel $user_id $job_id
fi