#!/usr/bin/env bash

set -e

script_dir=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
source $script_dir/constants.sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 nodeXXX"
    exit 1
fi

new_node=$1
config_file="$HOME/.ssh/config"

# Read in the file
lines=$(cat "$config_file")

# Find the line with the 3-digit code in it
if [[ ! $lines =~ "Host om" ]]; then
    echo "No existing om config found, adding one to your ~/.ssh/config file"
    # Append the new configuration to the end of the file
    new_config="
Host om
    HostName $remote_login_server
    ForwardAgent yes
    ForwardX11 yes
    ForwardX11Trusted yes
    User $remote_user
    "
    lines+="$new_config"
fi

# Find the line with the 3-digit code in it
if [[ $lines =~ "Host omnode" ]]; then
    # Replace the 3-digit code with the new one
    lines=$(echo "$lines" | sed -E "s/HostName node[0-9]{3}/HostName $new_node/")
else
    echo "No existing omnode config found, adding one to your ~/.ssh/config file"
    # Append the new configuration to the end of the file
    new_config="
Host omnode
    HostName $new_node
    ProxyJump om
    ForwardAgent yes
    ForwardX11 yes
    ForwardX11Trusted yes
    User $remote_user
    "
    lines+="$new_config"
fi

echo "$lines" > "$config_file"