#!/bin/bash

# This script is used to start the ssh service on Openmind

# Source the configuration variables
root=$(dirname $(readlink -f $0))
source $root/om_config.sh

ssh -tX $user_id@openmind.mit.edu "cd $remote_initial_dir ; bash --login"